### ISSUE TITLE
Define S4 class

### ISSUE THREAD

**Issue by jonesor** [jonesor/Rcompadre#1]
@tdjames1 and @iainmstott are handling this

**Comment by tdjames1** [comment]
We've decided to create two classes: CompadreData which corresponds to the existing DB object, holding the metadata together with the corresponding list of matrices, and CompadreMatrix which will hold a set of matrices (A, U, F and C) together with matrix specific information (e.g. definition of matrix stages currently held in the compadre$matrixClass list).

Accessor functions will provide access to the actual matrices e.g.

    getMatA(obj)

returns the A matrix (or matrices) associated with the object `obj`.

**Comment by jonesor** [comment]
This sounds great.

**Comment by jonesor** [comment]
The class is now defined.
