### ISSUE TITLE
suggestion for additional calculations  across matrices: mat_sd and mat_median

### ISSUE THREAD

**Issue by darrennorris** [jonesor/Rcompadre#136]
Maybe users would find additional options for element wise calculations across matrices useful.
To calculate standard deviations and median values I use mat_sd and mat_median adapted from "mat_mean"......copies below...
Best,
Darren

mat_sd <- function(x, na.rm = FALSE){
  n_row <- vapply(x, nrow, numeric(1))
  n_col <- vapply(x, ncol, numeric(1))
  if (length(unique(n_row)) != 1 | length(unique(n_col)) != 
      1) {
    stop("All matrices in list must be of same dimension")
  }
  if (na.rm) 
  x <- lapply(x, Rcompadre:::zero_NA)
  n <- length(x) 	   
  rc <- dim(x[[1]]) 
  rownames_mat <- rownames(x[[1]])
  colnames_mat <- colnames(x[[1]])
  ar1 <- array(unlist(x), c(rc, n)) 	   
  mat_out <- apply(ar1, c(1, 2), sd) 
  rownames(mat_out) <- rownames_mat
  colnames(mat_out) <- colnames_mat
  return(mat_out)
  }

mat_median <- function(x, na.rm = FALSE){
  n_row <- vapply(x, nrow, numeric(1))
  n_col <- vapply(x, ncol, numeric(1))
  if (length(unique(n_row)) != 1 | length(unique(n_col)) != 
      1) {
    stop("All matrices in list must be of same dimension")
  }
  if (na.rm) 
    x <- lapply(x, Rcompadre:::zero_NA)
  n <- length(x) 	   
  rc <- dim(x[[1]]) 	   
  rownames_mat <- rownames(x[[1]])
  colnames_mat <- colnames(x[[1]])
  ar1 <- array(unlist(x), c(rc, n)) 	   
  mat_out <- apply(ar1, c(1, 2), median) 
  rownames(mat_out) <- rownames_mat
  colnames(mat_out) <- colnames_mat
  return(mat_out)
}

**Comment by jonesor** [comment]
Hi Darren - good suggestion. Thanks for this! I have added those functions (including additional documentation and unit tests) to the development version of the package. You can load that version with: 

```
remotes::install_github("jonesor/Rcompadre", ref = "devel")
```

It would be great if you could take a quick look and let me know if you spot any issues!
