### ISSUE TITLE
popbio should be popdemo

### ISSUE THREAD

**Issue by bramdhondt** [jonesor/Rcompadre#142]
Dear, I am making my first steps in the _Rcompadre_ world.

I noticed a small but significant error on [your introductory page](https://jonesor.github.io/Rcompadre/index.html).

In the line `compadre_sub$lambda <- sapply(matA(compadre_sub), popbio::eigs, what = "lambda")`, `popbio` should be `popdemo`!

Kind regards,
Bram D'hondt ([profile](https://pureportal.inbo.be/en/persons/bram-dhondt-2))
Belgium

**Comment by jonesor** [comment]
Well-spotted, and thanks for pointing the error out. 
I have fixed it now.
