### ISSUE TITLE
Add Travis/Appveyor to `master` branch?

### ISSUE THREAD

**Issue by levisc8** [jonesor/Rcompadre#17]
Since we need a stable `master` branch for workshops (and since the master branch is now stable after a807f7a!), does it make sense to add continuous integration to make sure all pushes/pull requests to `master` are checked properly? If you're interested, you can read more on what continuous integration does in jonesor/Rage#9 and [here](http://r-pkgs.had.co.nz/check.html#travis).

If so, @jonesor (or someone else with administrative privileges) will need to activate it from the Github page (Settings -> Integrations & Services). From there, you can grant access to Travis-CI and it should redirect you to the Travis homepage so you can activate it from that end as well. Once that account is activated, I can set up the .travis.yml file. 

Thoughts?

**Comment by jonesor** [comment]
I have done this now. I've used just the default options, so please go ahead and make changes to the yml file if you think it is necessary.

**Comment by levisc8** [comment]
Cool, thanks for letting me know! I'll set it up to build on r-release and r-oldrelease later tonight. 

It may be worthwhile to add Appveyor support to cover all of operating system X R version combos (it builds with 3 versions of R on Windows). Setting it up is basically the same as setting up travis, just run `devtools::use_appveyor()` instead and follow the directions.

**Comment by jonesor** [comment]
AppVeyor sounds neat. I've added it. 
Thanks for taking a look later!
