### ISSUE TITLE
subsetDB not subsetting slot matrixClass

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rcompadre#19]
Function `subsetDB` does not currently subset slot `matrixClass`. This was my fault... I mistakenly removed the line:

`ssdb$matrixClass <- ssdb$matrixClass[subsetID]`

**Comment by levisc8** [comment]
This is only an issue with the `master` branch. The `CompadreM` class contains the `matrixClass` variable now; I think there was some confusion when converting back to the old method so that a teaching version  of the package still existed.

Either way, it should work now.
