### ISSUE TITLE
development package name

### ISSUE THREAD

**Issue by iainmstott** [jonesor/Rcompadre#21]
Suggestion: for the popdemo development package branch I use the package name 'popdemoDev' instead: perhaps this would be an idea for Rcompadre and Rage too. It means you can have both packages installed on your machine at the same time: one which works and one which may be buggy. 

Before merging the development branch into master you need to make sure you change it, though. And then change it back once the merge is completed.

This would be a problem if code included any RcompadreDev::function(... but at least in popdemo this isn't the case. Maybe I'm not doing things 'properly' (although it got past the CRAN pearly gates so I guess it should be good enough)

**Comment by jonesor** [comment]
Sounds like a good idea. 
I have just merged your pull request #24 to the devel branch. I'll try to remember to change the package name before I merge the devel branch with the master.
