### ISSUE TITLE
indexing within subsetDB

### ISSUE THREAD

**Issue by iainmstott** [jonesor/Rcompadre#22]
It would be good to have the ability in subsetDB to index using numbers or variable values that aren't Boolean, i.e. rather than `SpeciesAccepted == "Acinonyx_jubatus" | SpeciesAccepted == "Panthera_leo"`, to use `SpeciesAccepted = c("Panthera_leo", "Acinonyx_jubatus")`. Note these aren't in alphabetical order; it would be nice if the function returned them in the user's desired order.

Otherwise (and perhaps easier to implement / more useful), rather than a Boolean variable it would be good to be able to use e.g. `subsetDB(comadre, c(990, 646, 461, 1754, 1927) )` and the function would return a database with those numbers, in that order.

**Comment by tdjames1** [comment]
I'm not sure about this. 

1. It is already possible to specify a vector of variable values you want to match using `%in%`:
```subsetDB(mydb, SpeciesAccepted %in% c("Acinonyx_jubatus", "Panthera_leo"))```

2. Numeric indexing presupposes people know which rows they want and has the potential to get them into trouble if the data isn't organised the way they thought. Unless each entry has a unique numeric ID, which, at present, it doesn't.

**Comment by iainmstott** [comment]
Sorry, I wasn't clearer.

The first point is also about the order of the matrices (as number 2); just with species rather than rows.

If you're working with a small subset of the database, you might just want them in a certain order (doing this is what led me to create the issue; it's useful to have the matrices in e.g. phylogenetic order). Also with the new `[` method for the database, it would be good if it worked as intuitively (in the same way) as for a `data.frame`. Rather than seeing the databases as matrices with attached data, I think we should think of it as data with attached matrices: people are usually working and subsetting using the data. I don't think there's any harm in getting `subsetDB` to return the database in the order dictated by a numeric index or character string, if the we make sure the function itself (and therefore the `[` method) always makes sure the matrices and the metadata are associated with one another (and that's easy to do). In fact, giving people this intuitive method may prevent people making such mistakes as they never have to go into the data and work with the metadata slots and the matrix slots separately.

The point about unique IDs still holds, and something of us on the core committee are pushing for. We need them, there's just a lot of disagreement about what they should look like.

Hope that makes sense

**Comment by tdjames1** [comment]
Thanks for clarifying. I hadn't really registered the overall point about ordering (possibly because I haven't wanted/needed this myself).

> Rather than seeing the databases as matrices with attached data, I think we should think of it as data with attached matrices: people are usually working and subsetting using the data.

Agreed!

> if [...] we make sure the function itself (and therefore the [ method) always makes sure the matrices and the metadata are associated with one another

I'm definitely keen for that association to be built in.
