### ISSUE TITLE
Move matrix-level functions to Rage?

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rcompadre#28]
Four functions in Rcompadre act on individual matrices (i.e. their first argument is `matA`, or `matU`, etc.), and so I think would fit more naturally into Rage. These are:

`collapseMatrix`, `identifyReprodStages`, `rearrangeMatrix`, and `splitMatrix`.

Two of these (`collapseMatrix` and `rearrangeMatrix`) are used by `Rage::standardizedVitalRates`, so having them in the same package would be nice. None of the four functions are called by other functions in Rcompadre, so moving them shouldn't break anything.

**Comment by jonesor** [comment]
OK - I think that makes sense. Do you agree @robcito? If so I will move them over.

**Comment by iainmstott** [comment]
Sounds like a good plan to me! @jonesor maybe you can make that change (I assume nothing in RCompadre depends on those functions)

**Comment by jonesor** [comment]
I have dropped these four from the Rcompadre (Dev) package. They should be placed in Rage (Dev) package ASAP

**Comment by patrickbarks** [comment]
The 4 fns are already in Rage devel (from pull request jonesor/Rage#34), so closing issue.
