### ISSUE TITLE
Create cleanDB function

### ISSUE THREAD

**Issue by jonesor** [jonesor/Rcompadre#3]
Function to remove matrices that do not pass a series of (independent) tests.
e.g. ergodicity, primitivity, reducible, splitness etc.

**Comment by tdjames1** [comment]
@patrickbarks: Could you change the name of the function to `cleanDB`? I suggest that we use capitalised names for classes only.

**Comment by tdjames1** [comment]
I'm getting an error when I try to run `CleanDB(compadre_object)`:

    Error: 'isErgodic' is not an exported object from 'namespace:popdemo'

**Comment by patrickbarks** [comment]
Changed name to cleanDatabase and added documentation. No more error from isErgodic.
