### ISSUE TITLE
Rename classes

### ISSUE THREAD

**Issue by iainmstott** [jonesor/Rcompadre#38]
Following discussions with Owen, we felt it may make sense to change the names of the classes. The database is called `CompadreData`, but all of our functions use the syntax "DB" (`subsetDB`, `cleanDB`, `compareDBs`, etc.). Similarly, we use "mat" to refer to matrices (`matA`, `matU`, etc.) but the matrix-focused class is `CompadreM`. The proposal is to change these: `CompadreDB` and `CompadreMat` respectively. 

This may confuse us developers initially, and although users may not have to interact so much with the classes directly, it could make life better for anyone who wants to build on the package, specifically the classes, as well as anyone wanting to convert between the old and the new data structures.

Continuity is king

**Comment by iainmstott** [comment]
This may also help with #37 as it frees up the compadreData name for use there and in the slot

This might happen quickly (workshop time constraints again), so please shout at me if you think it's stupid

**Comment by levisc8** [comment]
Seems reasonable to me

**Comment by jonesor** [comment]
@iainmstott Did you make these changes yet in your branch? I would like to implement them in the `jonesor/dev` branch. Do you want to implement that or shall I?

**Comment by iainmstott** [comment]
Not yet! I got a certain way and then ran out of time. It's more involved than you might expect (lots of functions using methods associated with the previous "data" slot which needed to be addressed... And you can't just find and replace something as generic as "data" (my bad). I won't be able to push changes before Tuesday earliest... Sorry

**Comment by jonesor** [comment]
Closing this - I think all the changes were taken care of! Thanks!
