### ISSUE TITLE
Write split function

### ISSUE THREAD

**Issue by jonesor** [jonesor/Rcompadre#4]
Split - to split the database into two database objects, one matching a criteria, the other not.

**Comment by patrickbarks** [comment]
I think this operation would be better left to `subset`, particularly with the tidy version of `db`, e.g.

```
sub1 <- subset(db, (...))
sub2 <- subset(db, !(...))
```

A `split` function would require extra code just to access the two slots, e.g.

```
db_split <- split(db, ...)
sub1 <- db_split[[1]]
sub2 <- db_split[[2]]
```

**Comment by jonesor** [comment]
I also now think this should be left to subset. Closing.
