### ISSUE TITLE
Speed up validCompadreM() checks

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rcompadre#41]
... and therefore also `asCompadreData()` and `convertLegacyDB()`.

The conversion for COMPADRE_v.X.X.X takes 11-12 seconds on my computer, ~70% of which is due to the `validCompadreM()` checks. The use of `data.frame` for the `dims` object is causing most of the overhead. If `dims` is instead constructed as a matrix, the conversion time on my computer is reduced from ~11.5 to ~4.5 seconds. E.g.

```
dims <- cbind(matA = dim(object@matA),
              matU = dim(object@matU),
              matF = dim(object@matF),
              matC = dim(object@matC))
```

I think we can get it down to about 3.5 s with additional optimization.

**Comment by jonesor** [comment]
Done. So closing this one.
