### ISSUE TITLE
Create function "merge" for compadre.

### ISSUE THREAD

**Issue by jonesor** [jonesor/Rcompadre#5]
Merge 2 compadre databases together.

**Comment by levisc8** [comment]
Hi @DannyLBuss, I had to write a function merge together multiple subsets of the COM(P)ADRE to create the data sets to be included in the package. It's probably not perfect, but I've included it in the _data-raw/createDataSets.R_ file. It might be a good starting place for creating this if you haven't already started.

**Comment by jonesor** [comment]
The function mergeDBs does this. It works with pairs of databases only. 
Still needs to be thoroughly checked.
