### ISSUE TITLE
Online documentation

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rcompadre#50]
I think lots of R users only read vignettes online, rather than within R.

Until we're on CRAN (which publishes HTML vignettes), and since GitHub no longer renders Rmarkdown, I think it would be good to 'manually' publish formatted versions of our vignettes (perhaps including the workshop materials, @jonesor).

One option is to just render the vignettes as regular markdown and host them on the Rcompadre repo, and perhaps include links in the README. Though I'm not sure exactly how to do this... I think we'd have to specify multiple output formats in the Rmd header.

Some [quick Googling](https://stackoverflow.com/questions/39662365/knit-one-markdown-file-to-two-output-files) makes me think it's possible.

**Comment by patrickbarks** [comment]
Relatedly, in the longer-term, I think it would be cool to host something like 'case studies', or a gallery of example analyses with Rcompadre. Short, reproducible, markdown documents that illustrate interesting analyses. Could be solicited widely from contributors and users.

**Comment by levisc8** [comment]
Maybe we could set up a site w/ [pkgdown](https://pkgdown.r-lib.org/articles/pkgdown.html)? I think we could even set it up as sub-site (not sure what the term is) of www.compadre-db.org/.com. 

It looks like it will automatically build the vignettes and provide pages for each function/.Rd file every time we update them.

**Comment by patrickbarks** [comment]
Wow, ya. It's really easy, and looks great. 

Could also configure this through GitHub Pages -- just requires a couple clicks by Owen, and the url would be http://jonesor.github.io/Rcompadre

**Comment by jonesor** [comment]
That's fantastic! 
I *think* I have set this up correctly now. Its currently a 404 page at [http://jonesor.github.io/Rcompadre](http://jonesor.github.io/Rcompadre), but I think it will deploy via the Travis-CI system shortly.

**Comment by patrickbarks** [comment]
For the GitHub Pages configuration, I think the source needs to be "master branch docs/ folder" (can change under 'Settings'). That should be all that's needed now, as far as I can tell.

(I think the Travis CI deploy_site bit is just to make it automatically regenerate when we push a new release.) But we can always regenerate manually too, if we make substantial changes.

**Comment by patrickbarks** [comment]
Actually I see now that Travis has built the site in the gh-pages branch, and http://jonesor.github.io/Rcompadre works. But 3/4 of the Travis builds failed because of the deploy_site bit (the latest Appveyor builds passed). Not sure why exactly that part is failing. I'll try a minor push to trigger another build.

If it still doesn't work, suggest switching GitHub Pages to "master branch docs/ folder". If the site works, then can remove the auto-deploy section from .travis.yml, and hopefully the build will succeed.

**Comment by jonesor** [comment]
Ah - that makes sense.
I have set that now.

**Comment by patrickbarks** [comment]
@jonesor suggest adding website/description/topics to header of the GitHub repo. I've read these can help with searchability. You can update by clicking "Edit" and "Manage topics" at the top of the repo.

My suggestions (e.g.):

Description:
An R package to work with the COM(P)ADRE Matrix Population Model Databases

Website:
http://jonesor.github.io/Rcompadre

Topics:
- r
- rstats
- r-package
- demography
- demographic-analysis
- ecological-modelling
