### ISSUE TITLE
Add brief overview of tibbles to documentation

### ISSUE THREAD

**Issue by patrickbarks** [jonesor/Rcompadre#51]
Probably in 'Getting Started' vignette and maybe README. Could include link to [tibble vignette](https://cran.r-project.org/web/packages/tibble/vignettes/tibble.html), perhaps brief summary of differences from `data.frame`, and tips for changing default setting, e.g.

```
options(tibble.print_max = Inf) # always print all rows
options(tibble.width = Inf)     # always print all columns
```

**Comment by jonesor** [comment]
Closed with #90
