### ISSUE TITLE
as_cdb bug?

### ISSUE THREAD

**Issue by jonesor** [jonesor/Rcompadre#59]
From Haydee:

> We noticed that the the function `as_cdb` changes the amount of data stored in the R objects. Eg. When the function as_cdb is not used to convert the loaded r objects, `Clarkia_xantiana_subsp._xantiana` exists (at least with one matrix), if the `as_cdb` function is run, then the species disappears

**Comment by patrickbarks** [comment]
I just downloaded COMPADRE 5.0.0, and there do not seem to be any rows with SpeciesAuthor "Clarkia_xantiana_subsp._xantiana" (or even Genus "Clarkia"), either in the original list format or new cdb format.

It is in the X.X.X version, however (both original and cdb), so perhaps it was mistakenly removed from the new COMPADRE release?

**Comment by jchecastaldo** [comment]
Hi Patrick - i just checked again and it is as you say, no Clarkia anywhere in 5.0.0. I have no idea what was happening when we saw that (Jun 20). But looks like it's resolved now. Thanks for looking into it.
