### ISSUE TITLE
Rename master branch

### ISSUE THREAD

**Issue by iainmstott** [jonesor/Rcompadre#84]
In solidarity with the BLM movement, GitHub and Git users worldwide have started renaming their 'master' branches to something with lesser connotation of slavery. I propose we do the same for the Rcompadre package. Github now uses 'main', which I think is a good option.

**Comment by jonesor** [comment]
This has been on my mind. I also think it's a good idea and will implement it soon!

**Comment by jonesor** [comment]
I have now done this with #86.
I *think* I have changed every reference to `master`, for example with the continuous integration tools - we'll soon find out!
