### ISSUE TITLE
Change name of matrixClass to MatrixClass for consistency 

### ISSUE THREAD

**Issue by jonesor** [jonesor/Rcompadre#94]
Perhaps not a big deal but I think we should be consistent with cases across functions.

**Comment by jonesor** [comment]
This function is in `ClassUnionMethods`

**Comment by jonesor** [comment]
OK - I can see that the names of the objects within the com(p)adre download are `metadata`, `**matrixClass**`, `mat` and `version`.
Although the **function** to obtain matrix class information should be called `MatrixClass` for consistency with the other functions of this sort, the OBJECT is called `matrixClass` (small m). I, therefore, think that for the avoidance of confusion we could keep the function as is (`matrixClass`, small m)
What do you think @iainmstott and @tdjames1?

**Comment by tdjames1** [comment]
Yes, the convention that we used for those accessors originally was to follow the naming of the elements of the `compadre` object: `metadata`, `matrixClass` etc. But the columns of the `matrixClass` table are called `MatrixClassOrganized` etc which leads to the inconsistency for accessors for those elements. I think I would agree with leaving `matrixClass` as it is.

**Comment by jonesor** [comment]
Great - thanks @tdjames1! I'll close this issue, and leave the name of the function as it is.
